[provisioning]
source = "manual"
connection_string = 
 
[agent]
name = "edgeAgent"
type = "docker"
 
[agent.config]
image = "mcr.microsoft.com/azureiotedge-agent:1.1"
 
[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"
 
[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"
 
[moby_runtime]
uri = "unix:///var/run/docker.sock"
network = "azure-iot-edge"
